apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::990403209400:user/TF-user2
      username: tf-user2
      groups:
        - system:masters
